version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # MYSQL_USER: test
      # MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: db
    volumes:
    - ../server/src/db/scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306

  server:
    build:
      context: ../server
    container_name: server
    restart: always
    environment:
      DB_URL: root:test@tcp(mysql:3306)/db
      S3_URL: http://minio:9000
      AWS_ACCESS_KEY: testtest
      AWS_SECRET_KEY: testtest
      AWS_REGION: us-east-1
      RABBITMQ_ADDRESS: amqp://guest:guest@rabbitmq:5673/
    ports:
    - 8080:8080
    depends_on:
      - mysql
      - minio
      - rabbitmq
      
  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001" 
    environment:
      MINIO_ACCESS_KEY: testtest
      MINIO_SECRET_KEY: testtest
    ports:
    - 9000:9000
    - 9001:9001
    volumes:
    - ./temp/storage/minio:/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5673
      - 15672:15672
    volumes:
      - ./temp/rabbitmq/data:/var/lib/rabbitmq/
      - ./temp/rabbitmq/log/rabbitmq/log/:/var/log/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro


    
  
